### ISSUE TITLE
Strcat problems

### ISSUE THREAD

**Issue by Freyj** [Freyj/CSDungeon#1]
strcat cause bad access errors (according to valgrind)

**Comment by E1drad** [comment]
Resolve : 
.      initialization using "strcpy (buffer, "aString" );
and by
.      strcpy (buffer, "aString");
.      message = strcat(message, bufferGenMessage);
when we need to concatenate the message with a literal.

**Comment by E1drad** [comment]
Resolve : 
.      initialization using "strcpy (buffer, "aString" );
and by
.      strcpy (buffer, "aString");
.      message = strcat(message, bufferGenMessage);
when we need to concatenate the message with a literal.
